void TestException();

int main()
{
    TestException();
}